block.settings.openchurch_core_newsletter:
  type: block_settings
  label: 'Newsletter block'
  mapping:
    action:
      type: string
      label: 'Form Action'
    title:
      type: string
      label: 'Title'
    description:
      type: string
      label: 'Description'
